### ISSUE TITLE
Cannot use HW version 18 or 19 (Hardware Version/Compatibility Level)

### ISSUE THREAD

**Issue by peterchmelar** [AdrianBegg/VMware.Cloud.Director.Community#1]
VMware.Cloud.Director.Community/tree/master/Public/ProviderVDC)/**New-CIPVDC.ps1** line 59 does not contain a reference to _vmx-18 and vmx-19_, therefore these HW versions are not available for usage.
To resolve the issue it should be sufficient to append mentioned _vmx versions_ to the code in line 59:
` [ValidateNotNullorEmpty()] [ValidateSet("vmx-07","vmx-08","vmx-09","vmx-10","vmx-11","vmx-12","vmx-13","vmx-14","vmx-15","vmx-17", "vmx-18", "vmx-19")] $HardwareVersion = "vmx-17",`

**Comment by AdrianBegg** [comment]
Thanks Peter for reporting and for the contribution. PR #2 closes this issue.
